# Site settings
title: World Wide Widgets
description: we make stuff
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://worldwidewidgets.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: World Wide Widgets
user_description: describe what the hell we do
user_title: worsn't greatestn't company
email: companyemailorsomething@gmail.com
# twitter_username: lorem_ipsum
instagram_username: our instagram
facebook_username: our facebook
linkedin_username: our linkedin?
github_username:  worldwidewidgets
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

